// Unity build: all Catch2 test suites in a single translation unit
#include "basic_test.cpp"
#include "resource_test.cpp"
#include "callback_test.cpp"
#include "version_test.cpp"
#include "lookup_test.cpp"
#include "reload_test.cpp"
#include "edge_test.cpp"
#include "reflection_test.cpp"
#include "closed_test.cpp"
#include "logging_test.cpp"
#include "rcu_config_test.cpp"
#include "concurrency_test.cpp"