/*
 * Copyright 2026 Sukanle(https://github.com/Sukanle)
 *
 * Licensed under the Apache License, Version 2.0.
 */
#ifndef SKL_ABIX_RUNTIME_REGISTRY_H
#define SKL_ABIX_RUNTIME_REGISTRY_H

#include <stddef.h>
#include <stdint.h>

#include "metadata_registry.h"
#include "runtime_descriptor.h"

namespace skl::abix::runtime {

// Generated projections may specialize this trait for their native C++ type.
// Keeping the primary template incomplete makes an unregistered type a
// compile-time error rather than a name-based runtime fallback.
template<typename T>
struct TypeTraits;

enum class RuntimeRegisterStatus : uint32_t {
    ok = 0,
    invalid_module,
    duplicate_type,
    capacity_exceeded,
    unknown_type_reference,
    // Boundary #1: two modules claim the same TypeID with different layouts.
    layout_conflict,
};

struct RuntimeRegistryEntry {
    const TypeDescriptor *descriptor;
    const model::TypeDesc *canonical;
    const model::TypeLayout *layout;
    // Module ABI version this entry belongs to. The same TypeID may be
    // registered once per version (ABI evolution), each with its own layout;
    // find_type() selects the entry for an exact (TypeID, version) pair.
    uint32_t version;
};

template<size_t Capacity = 64>
class RuntimeRegistry {
public:
    using CanonicalRegistry = MetadataRegistry<Capacity>;

    RuntimeRegisterStatus register_module(const ModuleDescriptor &module) noexcept {
        return register_module(module, module_version(module));
    }

    // Versioned registration: the same TypeID may coexist under distinct module
    // ABI versions with different layouts. Only a repeated TypeID within the
    // *same* version is a Boundary #1 layout conflict.
    RuntimeRegisterStatus register_module(const ModuleDescriptor &module, uint32_t version) noexcept {
        // Load-time cross-module TypeID validation happens in check_module();
        // register_module only mutates once the whole module is known safe.
        const auto status = check_module(module, version);
        if (status != RuntimeRegisterStatus::ok) return status;

        for (uint32_t i = 0; i < module.type_count; ++i) {
            const auto &type = module.types[i];
            // A compatible duplicate already lives in the registry for this
            // version; the two modules share the existing canonical record.
            if (find_type(type.type_id, version)) continue;
            // Import the canonical TypeDesc/TypeLayout directly from the
            // ModuleDescriptor (which was generated by AMC from the one
            // AbiModule).  We DO NOT reconstruct them from the runtime
            // projection — the canonical arrays are the one ABI truth.
            const auto *canonical_type = &module.canonical_types[i];
            const auto *canonical_layout = &module.canonical_layouts[i];
            // The compact canonical registry keeps one layout per TypeID (the
            // first version to claim it). Later versions still register their
            // own entry below, referencing this module's canonical arrays.
            if (_canonical.find_by_id(type.type_id) == nullptr) {
                const auto reg = _canonical.register_type(canonical_type, canonical_layout);
                if (reg == RegisterStatus::layout_conflict) return RuntimeRegisterStatus::layout_conflict;
                if (reg != RegisterStatus::ok && reg != RegisterStatus::already_registered)
                    return RuntimeRegisterStatus::invalid_module;
                if (reg == RegisterStatus::already_registered) continue;
            }
            if (_count == Capacity) return RuntimeRegisterStatus::capacity_exceeded;
            _entries[_count++] = {&type, canonical_type, canonical_layout, version};
        }
        return RuntimeRegisterStatus::ok;
    }

    // Dry-run validation for a candidate module against everything already
    // registered. This is the AI-PM Boundary #1 check: a TypeID that appears
    // in two modules *of the same version* must resolve to the same LayoutHash.
    RuntimeRegisterStatus check_module(const ModuleDescriptor &module) const noexcept {
        return check_module(module, module_version(module));
    }

    RuntimeRegisterStatus check_module(const ModuleDescriptor &module, uint32_t version) const noexcept {
        if (!valid(module)) return RuntimeRegisterStatus::invalid_module;
        size_t new_types = 0;
        for (uint32_t i = 0; i < module.type_count; ++i) {
            const auto &type = module.types[i];
            if (duplicate_in_module(module, i)) return RuntimeRegisterStatus::duplicate_type;
            if (!valid_layout(type)) return RuntimeRegisterStatus::invalid_module;
            if (const auto *existing = find_type(type.type_id, version)) {
                if (!CanonicalRegistry::same_layout(existing->layout, &module.canonical_layouts[i]))
                    return RuntimeRegisterStatus::layout_conflict;
            } else {
                ++new_types;
            }
        }
        if (new_types > Capacity - _count) return RuntimeRegisterStatus::capacity_exceeded;
        for (uint32_t i = 0; i < module.type_count; ++i) {
            const auto &type = module.types[i];
            for (uint32_t j = 0; j < type.field_count; ++j)
                if (!known_type(module, type.fields[j].type_id)) return RuntimeRegisterStatus::unknown_type_reference;
        }
        for (uint32_t i = 0; i < module.function_count; ++i) {
            const auto &function = module.functions[i];
            if (!known_type(module, function.return_type)) return RuntimeRegisterStatus::unknown_type_reference;
            for (uint32_t j = 0; j < function.parameter_count; ++j)
                if (!known_type(module, function.parameters[j].type_id))
                    return RuntimeRegisterStatus::unknown_type_reference;
        }
        return RuntimeRegisterStatus::ok;
    }

    // Consistency hook for the frozen registry: every runtime entry must still
    // resolve to the exact canonical record that was validated at load time.
    // Versioned entries legitimately differ from the compact canonical registry
    // (which keeps one layout per TypeID), so each entry is checked against its
    // own canonical arrays instead.
    RuntimeRegisterStatus validate() const noexcept {
        for (size_t i = 0; i < _count; ++i) {
            const auto &entry = _entries[i];
            if (!_canonical.find_by_id(entry.descriptor->type_id)) return RuntimeRegisterStatus::invalid_module;
            if (entry.canonical->id != entry.descriptor->type_id) return RuntimeRegisterStatus::invalid_module;
            if (entry.descriptor->layout_hash != entry.layout->layout_hash
                || entry.descriptor->size != entry.layout->size
                || entry.descriptor->align != entry.layout->align)
                return RuntimeRegisterStatus::layout_conflict;
        }
        return RuntimeRegisterStatus::ok;
    }

    // Versioned lookup: the descriptor registered for this exact (TypeID,
    // version) pair, or nullptr. This is the runtime half of AI-PA dispatch —
    // the adapter layer selects the version and asks for its descriptor.
    const RuntimeRegistryEntry *find_type(model::TypeId id, uint32_t version) const noexcept {
        for (size_t i = 0; i < _count; ++i) {
            if (_entries[i].descriptor->type_id == id && _entries[i].version == version) return &_entries[i];
        }
        return nullptr;
    }

    // Version-agnostic lookup returns the newest registered version of the
    // TypeID, which is the correct default when the caller does not pin one.
    const RuntimeRegistryEntry *find_by_id(model::TypeId id) const noexcept {
        const RuntimeRegistryEntry *best = nullptr;
        for (size_t i = 0; i < _count; ++i) {
            if (_entries[i].descriptor->type_id != id) continue;
            if (!best || _entries[i].version >= best->version) best = &_entries[i];
        }
        return best;
    }

    // The ABI version carried by a generated module descriptor is the leading
    // decimal integer of its version string ("1", "1.0", "2" -> 1, 1, 2). A
    // version with no leading digits maps to 0 (experimental/unversioned).
    static uint32_t parse_version(const char *text) noexcept {
        uint32_t value = 0;
        if (!text) return value;
        for (const char *p = text; *p >= '0' && *p <= '9'; ++p)
            value = value * 10 + static_cast<uint32_t>(*p - '0');
        return value;
    }

    static uint32_t module_version(const ModuleDescriptor &module) noexcept { return parse_version(module.version); }

    // Name lookup is intentionally omitted in the compact descriptor build.
    // Name strings live in a separate .abix.names section (or external .abix
    // file) for diagnostic use only; runtime contract validation uses type_id.
    // Use type_of<T>() or find_by_id() for runtime queries.
    const RuntimeRegistryEntry *find_by_name(const char *) const noexcept { return nullptr; }

    template<typename T>
    const RuntimeRegistryEntry *type_of() const noexcept {
        return find_by_id(TypeTraits<T>::type_id);
    }

    const RuntimeRegistryEntry *at(size_t index) const noexcept { return index < _count ? &_entries[index] : nullptr; }

    size_t size() const noexcept { return _count; }
    const CanonicalRegistry &canonical() const noexcept { return _canonical; }

private:
    bool known_type(const ModuleDescriptor &module, model::TypeId id) const noexcept {
        for (uint32_t i = 0; i < module.type_count; ++i)
            if (module.types[i].type_id == id) return true;
        return find_by_id(id) != nullptr;
    }

    bool duplicate_in_module(const ModuleDescriptor &module, uint32_t index) const noexcept {
        for (uint32_t i = 0; i < index; ++i)
            if (module.types[i].type_id == module.types[index].type_id) return true;
        return false;
    }

    static bool valid_layout(const TypeDescriptor &type) noexcept {
        return (type.align & (type.align - 1)) == 0 && type.align != 0;
    }

    RuntimeRegistryEntry _entries[Capacity == 0 ? 1 : Capacity]{};
    CanonicalRegistry _canonical{};
    size_t _count = 0;
};

}   // namespace skl::abix::runtime

#endif   // SKL_ABIX_RUNTIME_REGISTRY_H