#include "AMC/Core/Adapter.h"

#include <cctype>
#include <cstdint>
#include <map>
#include <utility>

#include <fmt/format.h>

namespace amc {
namespace {

std::string hash_literal(Hash128 value) {
    return fmt::format("0x{:016x}{:016x}", value.hi, value.lo);
}

// A 128-bit identity as two 64-bit C literal halves (a single 128-bit integer
// literal does not exist in C++).
std::string id_literal(Hash128 value) {
    return fmt::format("{{0x{:016x}ULL, 0x{:016x}ULL}}", value.lo, value.hi);
}

std::string cpp_string(const std::string &value) {
    std::string result = "\"";
    for (const char c : value) {
        if (c == '\\' || c == '"') result += '\\';
        result += c;
    }
    return result + '"';
}

using TypeKey = std::pair<uint64_t, uint64_t>;
using TypeMap = std::map<TypeKey, const Type *>;

TypeMap index_types(const AbiModule &module) {
    TypeMap map;
    for (const auto &type : module.types)
        map[{type.id.lo, type.id.hi}] = &type;
    return map;
}

const Field *field_at(const AbiModule &module, uint32_t index) {
    return index < module.fields.size() ? &module.fields[index] : nullptr;
}

std::string field_label(const AbiModule &module, uint32_t index) {
    const Field *field = field_at(module, index);
    return field != nullptr ? field->name : std::string("<default>");
}

// Byte width of a field's ABI type, resolved through the module's type index.
uint32_t field_type_size(const AbiModule &module, const TypeMap &types, uint32_t field_index) {
    const Field *field = field_at(module, field_index);
    if (field == nullptr) return 0;
    const auto it = types.find({field->type_id.lo, field->type_id.hi});
    return it != types.end() ? it->second->size : 0;
}

std::string int_type(uint32_t size) {
    switch (size) {
        case 1:  return "std::int8_t";
        case 2:  return "std::int16_t";
        case 4:  return "std::int32_t";
        case 8:  return "std::int64_t";
        default: return {};
    }
}

std::string float_type(uint32_t size) {
    switch (size) {
        case 4:  return "float";
        case 8:  return "double";
        default: return {};
    }
}

std::string adapter_fn(std::string_view source, std::string_view target, size_t index) {
    return fmt::format("{}_to_{}_{}", adapter_symbol(source), adapter_symbol(target), index);
}

}   // namespace

std::string adapter_symbol(std::string_view name) {
    std::string symbol;
    for (size_t i = 0; i < name.size(); ++i) {
        const char c = name[i];
        if (c == ':' && i + 1 < name.size() && name[i + 1] == ':') {
            symbol += '_';
            ++i;
        } else if (std::isalnum(static_cast<unsigned char>(c)) || c == '_') {
            symbol += c;
        } else {
            symbol += '_';
        }
    }
    if (symbol.empty() || std::isdigit(static_cast<unsigned char>(symbol[0]))) symbol = "_" + symbol;
    return symbol;
}

std::string generate_adapter(const AbiModule &source, const AbiModule &target, const AbiModule &report,
    const AdapterOptions &options, std::string &error) {
    error.clear();
    if (report.maps.empty()) {
        error = "no compatible mapping between the two artifacts";
        return {};
    }
    const TypeMap target_types = index_types(target);
    const TypeMap source_types = index_types(source);

    std::string out;
    out += "// Generated by AMC — ABI adapter.\n";
    out += "// source: ";
    out += source.package_name.empty() ? "?" : source.package_name;
    out += " abi_hash=";
    out += hash_literal(abi_hash(source));
    out += "\n";
    out += "// target: ";
    out += target.package_name.empty() ? "?" : target.package_name;
    out += " abi_hash=";
    out += hash_literal(abi_hash(target));
    out += "\n";
    out += "//\n";
    out += "// Raw-memory adapters derived from the ABIX mapping records. The\n";
    out += "// target buffer is fully zero-initialised, so add_default / skip_field\n";
    out += "// need no code; convert_int / convert_float are emitted as casts.\n";
    if (!options.shim) out += "#pragma once\n";
    out += "#include <cstddef>\n";
    out += "#include <cstdint>\n";
    out += "#include <cstring>\n";
    out += "\n";
    out += "namespace abix_adapter {\n\n";
    out += "struct TypeId { std::uint64_t lo; std::uint64_t hi; };\n\n";
    out += "struct Entry {\n";
    out += "    const char *source_name;\n";
    out += "    const char *target_name;\n";
    out += "    TypeId ids[2];        // [0] source, [1] target\n";
    out += "    const char *source_id;\n";
    out += "    const char *target_id;\n";
    out += "    std::uint32_t target_size;  // bytes to zero-initialise\n";
    out += "    void (*apply)(const void *, void *) noexcept;\n";
    out += "};\n\n";

    for (size_t i = 0; i < report.maps.size(); ++i) {
        const MapRecord &map = report.maps[i];
        const std::string fn = adapter_fn(map.source_name, map.target_name, i);
        const auto target_it = target_types.find({map.target_type.lo, map.target_type.hi});
        const uint32_t target_size = target_it != target_types.end() ? target_it->second->size : 0;

        out += "// ";
        out += map.source_name;
        out += " -> ";
        out += map.target_name;
        out += "\n";
        out += "// ";
        out += hash_literal(map.source_type);
        out += " -> ";
        out += hash_literal(map.target_type);
        out += "\n";
        out += "inline void ";
        out += fn;
        out += "(const void *source, void *target) noexcept {\n";
        if (target_size != 0) {
            out += "    std::memset(target, 0, ";
            out += fmt::to_string(target_size);
            out += ");\n";
        }
        for (const auto &operation : map.operations) {
            switch (operation.opcode) {
                case MapOpcode::copy_field:
                    out += "    std::memcpy(static_cast<std::uint8_t *>(target) + ";
                    out += fmt::to_string(operation.target_offset);
                    out += ",\n";
                    out += "                static_cast<const std::uint8_t *>(source) + ";
                    out += fmt::to_string(operation.source_offset);
                    out += ", ";
                    out += fmt::to_string(operation.byte_count);
                    out += ");";
                    out += "  // copy_field ";
                    out += field_label(source, operation.source_field);
                    out += " -> ";
                    out += field_label(target, operation.target_field);
                    out += "\n";
                    break;
                case MapOpcode::add_default:
                    out += "    // add_default ";
                    out += field_label(target, operation.target_field);
                    out += " (zero-initialised)\n";
                    break;
                case MapOpcode::skip_field:
                    out += "    // skip_field ";
                    out += field_label(source, operation.source_field);
                    out += "\n";
                    break;
                case MapOpcode::convert_int: {
                    const std::string from = int_type(field_type_size(source, source_types, operation.source_field));
                    const std::string to = int_type(field_type_size(target, target_types, operation.target_field));
                    if (from.empty() || to.empty()) {
                        out += "    // WARNING: convert_int ";
                        out += field_label(source, operation.source_field);
                        out += " -> ";
                        out += field_label(target, operation.target_field);
                        out += " has an unsupported width\n";
                        break;
                    }
                    out += "    *reinterpret_cast<";
                    out += to;
                    out += " *>(static_cast<std::uint8_t *>(target) + ";
                    out += fmt::to_string(operation.target_offset);
                    out += ") =\n";
                    out += "        static_cast<";
                    out += to;
                    out += ">(*reinterpret_cast<const ";
                    out += from;
                    out += " *>(static_cast<const std::uint8_t *>(source) + ";
                    out += fmt::to_string(operation.source_offset);
                    out += "));  // convert_int ";
                    out += field_label(source, operation.source_field);
                    out += " -> ";
                    out += field_label(target, operation.target_field);
                    out += "\n";
                    break;
                }
                case MapOpcode::convert_float: {
                    const std::string from = float_type(field_type_size(source, source_types, operation.source_field));
                    const std::string to = float_type(field_type_size(target, target_types, operation.target_field));
                    if (from.empty() || to.empty()) {
                        out += "    // WARNING: convert_float ";
                        out += field_label(source, operation.source_field);
                        out += " -> ";
                        out += field_label(target, operation.target_field);
                        out += " has an unsupported width\n";
                        break;
                    }
                    out += "    *reinterpret_cast<";
                    out += to;
                    out += " *>(static_cast<std::uint8_t *>(target) + ";
                    out += fmt::to_string(operation.target_offset);
                    out += ") =\n";
                    out += "        static_cast<";
                    out += to;
                    out += ">(*reinterpret_cast<const ";
                    out += from;
                    out += " *>(static_cast<const std::uint8_t *>(source) + ";
                    out += fmt::to_string(operation.source_offset);
                    out += "));  // convert_float ";
                    out += field_label(source, operation.source_field);
                    out += " -> ";
                    out += field_label(target, operation.target_field);
                    out += "\n";
                    break;
                }
            }
        }
        out += "}\n\n";
        out += "inline constexpr Entry ";
        out += fn;
        out += "_entry = {";
        out += cpp_string(map.source_name);
        out += ", ";
        out += cpp_string(map.target_name);
        out += ", {";
        out += id_literal(map.source_type);
        out += ", ";
        out += id_literal(map.target_type);
        out += "}, ";
        out += cpp_string(hash_literal(map.source_type));
        out += ", ";
        out += cpp_string(hash_literal(map.target_type));
        out += ", ";
        out += fmt::to_string(target_size);
        out += ", ";
        out += fn;
        out += "};\n\n";
    }

    out += "inline constexpr Entry entries[] = {\n";
    for (size_t i = 0; i < report.maps.size(); ++i) {
        const MapRecord &map = report.maps[i];
        out += "    ";
        out += adapter_fn(map.source_name, map.target_name, i);
        out += "_entry,\n";
    }
    out += "};\n";
    out += "inline constexpr std::size_t entry_count = ";
    out += fmt::to_string(report.maps.size());
    out += ";\n\n";

    out += "inline const Entry *find(const char *source_name, const char *target_name) noexcept {\n";
    out += "    for (const Entry &entry : entries)\n";
    out += "        if (std::strcmp(entry.source_name, source_name) == 0 &&\n";
    out += "            std::strcmp(entry.target_name, target_name) == 0)\n";
    out += "            return &entry;\n";
    out += "    return nullptr;\n";
    out += "}\n\n";

    out += "inline bool apply(const void *source, void *target, TypeId source_id,\n";
    out += "                  TypeId target_id) noexcept {\n";
    out += "    for (const Entry &entry : entries)\n";
    out += "        if (entry.ids[0].lo == source_id.lo && entry.ids[0].hi == source_id.hi &&\n";
    out += "            entry.ids[1].lo == target_id.lo && entry.ids[1].hi == target_id.hi) {\n";
    out += "            entry.apply(source, target);\n";
    out += "            return true;\n";
    out += "        }\n";
    out += "    return false;\n";
    out += "}\n\n";
    out += "}  // namespace abix_adapter\n";

    if (options.typed) {
        out += "\n";
        out += "// Typed specializations over the generated C++ projection\n";
        out += "// (namespace ";
        out += options.typed_namespace;
        out += "). Include the projection\n";
        out += "// header first, then define ABIX_ADAPTER_TYPED before this header.\n";
        out += "#include <ABIX/Bridge/Adapter.h>\n";
        out += "#ifdef ABIX_ADAPTER_TYPED\n";
        for (size_t i = 0; i < report.maps.size(); ++i) {
            const MapRecord &map = report.maps[i];
            out += "template <> struct ::skl::abix::bridge::Adapter<::";
            out += options.typed_namespace;
            out += "::";
            out += adapter_symbol(map.source_name);
            out += "_ABIX, ::";
            out += options.typed_namespace;
            out += "::";
            out += adapter_symbol(map.target_name);
            out += "_ABIX> {\n";
            out += "    static bool apply(void *target, const void *source) noexcept {\n";
            out += "        abix_adapter::";
            out += adapter_fn(map.source_name, map.target_name, i);
            out += "(source, target);\n";
            out += "        return true;\n";
            out += "    }\n";
            out += "};\n";
        }
        out += "#endif  // ABIX_ADAPTER_TYPED\n";
    }

    if (options.shim) {
        out += "\n";
        out += "// C ABI shim: compile this file into a shared library and load it\n";
        out += "// from a host that has no access to the C++ projection.\n";
        out += "extern \"C\" {\n";
        out += "std::size_t abix_adapter_count() noexcept { return abix_adapter::entry_count; }\n";
        out += "bool abix_adapter_apply(const char *source_name, const char *target_name,\n";
        out += "                        const void *source, void *target) noexcept {\n";
        out += "    const abix_adapter::Entry *entry = abix_adapter::find(source_name, target_name);\n";
        out += "    if (entry == nullptr) return false;\n";
        out += "    entry->apply(source, target);\n";
        out += "    return true;\n";
        out += "}\n";
        out += "}  // extern \"C\"\n";
    }
    return out;
}

}   // namespace amc
