#include "AMC/Core/Lua.h"

#include <cctype>

#include <fmt/format.h>

namespace amc {
namespace {

std::string hash_literal(Hash128 value) {
    return fmt::format("0X{:016x}{:016x}", value.hi, value.lo);
}

std::string cpp_string(const std::string &value) {
    std::string result = "\"";
    for (const char c : value) {
        if (c == '\\' || c == '"') result += '\\';
        if (c == '\n')
            result += "\\n";
        else if (c == '\r')
            result += "\\r";
        else if (c == '\t')
            result += "\\t";
        else
            result += c;
    }
    return result + '"';
}

}   // namespace

std::string lua_function_symbol(std::string_view name) {
    std::string symbol;
    symbol.reserve(name.size());
    for (size_t i = 0; i < name.size(); ++i) {
        const char c = name[i];
        if (c == ':' && i + 1 < name.size() && name[i + 1] == ':') {
            symbol += '_';
            ++i;
        } else if (std::isalnum(static_cast<unsigned char>(c)) || c == '_') {
            symbol += c;
        } else {
            symbol += '_';
        }
    }
    if (symbol.empty() || std::isdigit(static_cast<unsigned char>(symbol[0]))) symbol = "_" + symbol;
    return symbol;
}

std::string lua_entry_name(std::string_view package, std::string_view name) {
    if (!package.empty()) {
        const std::string prefix = std::string(package) + "_";
        if (name.size() > prefix.size() && name.compare(0, prefix.size(), prefix) == 0)
            return std::string(name.substr(prefix.size()));
    }
    return std::string(name);
}

std::string generate_lua_contract(const AbiModule &module, std::string &error) {
    error.clear();
    const std::string package = module.package_name.empty() ? "abix_module" : module.package_name;

    std::string out;
    out += "// Generated by AMC from ";
    out += package;
    out += " — Aue (Lua) boundary contract.\n";
    out += "// abi_hash = ";
    out += hash_literal(abi_hash(module));
    out += "\n";
    out += "// Do not edit; regenerate with `amc generate <file.abix> -l lua -o <file.hpp>`.\n";
    out += "#pragma once\n";
    out += "#include \"Aue/Aue.h\"\n";
    out += "\n";
    out += "namespace amc_generated {\n";
    out += "\n";

    for (const auto &function : module.functions) {
        out += "extern \"C\" int ";
        out += lua_function_symbol(function.name);
        out += "(lua_State *);  // ";
        out += function.name;
        out += " signature=";
        out += hash_literal(function.signature);
        out += "\n";
    }
    out += "\n";

    const size_t count = module.functions.empty() ? 1 : module.functions.size();
    out += "inline const aue::Entry lua_entries[";
    out += fmt::to_string(count);
    out += "] = {\n";
    for (const auto &function : module.functions) {
        out += "    {";
        out += cpp_string(lua_entry_name(package, function.name));
        out += ", ";
        out += fmt::to_string(static_cast<uint32_t>(function.parameters.size()));
        out += ", ";
        out += lua_function_symbol(function.name);
        out += "},\n";
    }
    if (module.functions.empty()) out += "    {nullptr, 0, nullptr},\n";
    out += "};\n\n";

    out += "inline const aue::Contract lua_contract = {\n";
    out += "    ";
    out += cpp_string(package);
    out += ",\n";
    out += "    ";
    out += cpp_string(hash_literal(abi_hash(module)));
    out += ",\n";
    out += "    lua_entries,\n";
    out += "    ";
    out += fmt::to_string(module.functions.size());
    out += ",\n";
    out += "};\n";
    out += "\n";
    out += "}  // namespace amc_generated\n";
    return out;
}

std::string generate_lua_conformance(const AbiModule &module, std::string &error) {
    error.clear();
    const std::string package = module.package_name.empty() ? "abix_module" : module.package_name;
    const std::string hash = hash_literal(abi_hash(module));

    std::string out;
    out += "-- Generated by AMC from ";
    out += package;
    out += " — Aue conformance script.\n";
    out += "-- Compiled-time metadata drives this test; run it under L0 and L1 and\n";
    out += "-- the observable output must be identical.\n";
    out += "-- abi_hash = ";
    out += hash;
    out += "\n";
    out += "local expected = {\n";
    for (const auto &function : module.functions) {
        out += "    ";
        out += cpp_string(lua_entry_name(package, function.name));
        out += ",\n";
    }
    out += "}\n";
    out += "local seen = 0\n";
    out += "for _, name in ipairs(expected) do\n";
    out += "    assert(type(counter[name]) == \"function\", \"missing binding: \" .. name)\n";
    out += "    seen = seen + 1\n";
    out += "end\n";
    out += "assert(counter._module == ";
    out += cpp_string(package);
    out += ", \"module mismatch\")\n";
    out += "assert(counter._abi_hash == ";
    out += cpp_string(hash);
    out += ", \"abi hash mismatch\")\n";
    out += "print(\"aue-conformance\", seen, counter._module)\n";
    return out;
}

}   // namespace amc
