#include "amc_adapter.h"

#include <cctype>
#include <cstdint>
#include <iomanip>
#include <map>
#include <sstream>
#include <utility>

namespace amc {
namespace {

std::string hash_literal(Hash128 value) {
    std::ostringstream out;
    out << "0x" << std::hex << std::setfill('0') << std::setw(16) << value.hi << std::setw(16) << value.lo;
    return out.str();
}

// A 128-bit identity as two 64-bit C literal halves (a single 128-bit integer
// literal does not exist in C++).
std::string id_literal(Hash128 value) {
    std::ostringstream out;
    out
        << "{0x"
        << std::hex
        << std::setfill('0')
        << std::setw(16)
        << value.lo
        << "ULL, 0x"
        << std::setw(16)
        << value.hi
        << "ULL}";
    return out.str();
}

std::string cpp_string(const std::string &value) {
    std::string result = "\"";
    for (const char c : value) {
        if (c == '\\' || c == '"') result += '\\';
        result += c;
    }
    return result + '"';
}

using TypeKey = std::pair<uint64_t, uint64_t>;
using TypeMap = std::map<TypeKey, const Type *>;

TypeMap index_types(const AbiModule &module) {
    TypeMap map;
    for (const auto &type : module.types)
        map[{type.id.lo, type.id.hi}] = &type;
    return map;
}

const Field *field_at(const AbiModule &module, uint32_t index) {
    return index < module.fields.size() ? &module.fields[index] : nullptr;
}

std::string field_label(const AbiModule &module, uint32_t index) {
    const Field *field = field_at(module, index);
    return field != nullptr ? field->name : std::string("<default>");
}

// Byte width of a field's ABI type, resolved through the module's type index.
uint32_t field_type_size(const AbiModule &module, const TypeMap &types, uint32_t field_index) {
    const Field *field = field_at(module, field_index);
    if (field == nullptr) return 0;
    const auto it = types.find({field->type_id.lo, field->type_id.hi});
    return it != types.end() ? it->second->size : 0;
}

std::string int_type(uint32_t size) {
    switch (size) {
        case 1:  return "std::int8_t";
        case 2:  return "std::int16_t";
        case 4:  return "std::int32_t";
        case 8:  return "std::int64_t";
        default: return {};
    }
}

std::string float_type(uint32_t size) {
    switch (size) {
        case 4:  return "float";
        case 8:  return "double";
        default: return {};
    }
}

}   // namespace

std::string adapter_symbol(std::string_view name) {
    std::string symbol;
    for (size_t i = 0; i < name.size(); ++i) {
        const char c = name[i];
        if (c == ':' && i + 1 < name.size() && name[i + 1] == ':') {
            symbol += '_';
            ++i;
        } else if (std::isalnum(static_cast<unsigned char>(c)) || c == '_') {
            symbol += c;
        } else {
            symbol += '_';
        }
    }
    if (symbol.empty() || std::isdigit(static_cast<unsigned char>(symbol[0]))) symbol = "_" + symbol;
    return symbol;
}

std::string generate_adapter(const AbiModule &source, const AbiModule &target, const AbiModule &report,
    const AdapterOptions &options, std::string &error) {
    error.clear();
    if (report.maps.empty()) {
        error = "no compatible mapping between the two artifacts";
        return {};
    }
    const TypeMap target_types = index_types(target);
    const TypeMap source_types = index_types(source);

    std::ostringstream out;
    out
        << "// Generated by AMC — ABI adapter.\n"
        << "// source: "
        << (source.package_name.empty() ? "?" : source.package_name)
        << " abi_hash="
        << hash_literal(abi_hash(source))
        << "\n"
        << "// target: "
        << (target.package_name.empty() ? "?" : target.package_name)
        << " abi_hash="
        << hash_literal(abi_hash(target))
        << "\n"
        << "//\n"
        << "// Raw-memory adapters derived from the ABIX mapping records. The\n"
        << "// target buffer is fully zero-initialised, so add_default / skip_field\n"
        << "// need no code; convert_int / convert_float are emitted as casts.\n";
    if (!options.shim) out << "#pragma once\n";
    out
        << "#include <cstddef>\n"
        << "#include <cstdint>\n"
        << "#include <cstring>\n"
        << "\n"
        << "namespace abix_adapter {\n\n"
        << "struct TypeId { std::uint64_t lo; std::uint64_t hi; };\n\n"
        << "struct Entry {\n"
        << "    const char *source_name;\n"
        << "    const char *target_name;\n"
        << "    TypeId ids[2];        // [0] source, [1] target\n"
        << "    const char *source_id;\n"
        << "    const char *target_id;\n"
        << "    std::uint32_t target_size;  // bytes to zero-initialise\n"
        << "    void (*apply)(const void *, void *) noexcept;\n"
        << "};\n\n";

    for (size_t i = 0; i < report.maps.size(); ++i) {
        const MapRecord &map = report.maps[i];
        const std::string fn =
            adapter_symbol(map.source_name) + "_to_" + adapter_symbol(map.target_name) + "_" + std::to_string(i);
        const auto target_it = target_types.find({map.target_type.lo, map.target_type.hi});
        const uint32_t target_size = target_it != target_types.end() ? target_it->second->size : 0;

        out
            << "// "
            << map.source_name
            << " -> "
            << map.target_name
            << "\n"
            << "// "
            << hash_literal(map.source_type)
            << " -> "
            << hash_literal(map.target_type)
            << "\n"
            << "inline void "
            << fn
            << "(const void *source, void *target) noexcept {\n";
        if (target_size != 0) out << "    std::memset(target, 0, " << target_size << ");\n";
        for (const auto &operation : map.operations) {
            switch (operation.opcode) {
                case MapOpcode::copy_field:
                    out
                        << "    std::memcpy(static_cast<std::uint8_t *>(target) + "
                        << operation.target_offset
                        << ",\n"
                        << "                static_cast<const std::uint8_t *>(source) + "
                        << operation.source_offset
                        << ", "
                        << operation.byte_count
                        << ");"
                        << "  // copy_field "
                        << field_label(source, operation.source_field)
                        << " -> "
                        << field_label(target, operation.target_field)
                        << "\n";
                    break;
                case MapOpcode::add_default:
                    out
                        << "    // add_default "
                        << field_label(target, operation.target_field)
                        << " (zero-initialised)\n";
                    break;
                case MapOpcode::skip_field:
                    out << "    // skip_field " << field_label(source, operation.source_field) << "\n";
                    break;
                case MapOpcode::convert_int: {
                    const std::string from = int_type(field_type_size(source, source_types, operation.source_field));
                    const std::string to = int_type(field_type_size(target, target_types, operation.target_field));
                    if (from.empty() || to.empty()) {
                        out
                            << "    // WARNING: convert_int "
                            << field_label(source, operation.source_field)
                            << " -> "
                            << field_label(target, operation.target_field)
                            << " has an unsupported width\n";
                        break;
                    }
                    out
                        << "    *reinterpret_cast<"
                        << to
                        << " *>(static_cast<std::uint8_t *>(target) + "
                        << operation.target_offset
                        << ") =\n"
                        << "        static_cast<"
                        << to
                        << ">(*reinterpret_cast<const "
                        << from
                        << " *>(static_cast<const std::uint8_t *>(source) + "
                        << operation.source_offset
                        << "));  // convert_int "
                        << field_label(source, operation.source_field)
                        << " -> "
                        << field_label(target, operation.target_field)
                        << "\n";
                    break;
                }
                case MapOpcode::convert_float: {
                    const std::string from = float_type(field_type_size(source, source_types, operation.source_field));
                    const std::string to = float_type(field_type_size(target, target_types, operation.target_field));
                    if (from.empty() || to.empty()) {
                        out
                            << "    // WARNING: convert_float "
                            << field_label(source, operation.source_field)
                            << " -> "
                            << field_label(target, operation.target_field)
                            << " has an unsupported width\n";
                        break;
                    }
                    out
                        << "    *reinterpret_cast<"
                        << to
                        << " *>(static_cast<std::uint8_t *>(target) + "
                        << operation.target_offset
                        << ") =\n"
                        << "        static_cast<"
                        << to
                        << ">(*reinterpret_cast<const "
                        << from
                        << " *>(static_cast<const std::uint8_t *>(source) + "
                        << operation.source_offset
                        << "));  // convert_float "
                        << field_label(source, operation.source_field)
                        << " -> "
                        << field_label(target, operation.target_field)
                        << "\n";
                    break;
                }
            }
        }
        out
            << "}\n\n"
            << "inline constexpr Entry "
            << fn
            << "_entry = {"
            << cpp_string(map.source_name)
            << ", "
            << cpp_string(map.target_name)
            << ", {"
            << id_literal(map.source_type)
            << ", "
            << id_literal(map.target_type)
            << "}, "
            << cpp_string(hash_literal(map.source_type))
            << ", "
            << cpp_string(hash_literal(map.target_type))
            << ", "
            << target_size
            << ", "
            << fn
            << "};\n\n";
    }

    out << "inline constexpr Entry entries[] = {\n";
    for (size_t i = 0; i < report.maps.size(); ++i) {
        const MapRecord &map = report.maps[i];
        const std::string fn =
            adapter_symbol(map.source_name) + "_to_" + adapter_symbol(map.target_name) + "_" + std::to_string(i);
        out << "    " << fn << "_entry,\n";
    }
    out
        << "};\n"
        << "inline constexpr std::size_t entry_count = "
        << report.maps.size()
        << ";\n\n";

    out
        << "inline const Entry *find(const char *source_name, const char *target_name) noexcept {\n"
        << "    for (const Entry &entry : entries)\n"
        << "        if (std::strcmp(entry.source_name, source_name) == 0 &&\n"
        << "            std::strcmp(entry.target_name, target_name) == 0)\n"
        << "            return &entry;\n"
        << "    return nullptr;\n"
        << "}\n\n";

    out
        << "inline bool apply(const void *source, void *target, TypeId source_id,\n"
        << "                  TypeId target_id) noexcept {\n"
        << "    for (const Entry &entry : entries)\n"
        << "        if (entry.ids[0].lo == source_id.lo && entry.ids[0].hi == source_id.hi &&\n"
        << "            entry.ids[1].lo == target_id.lo && entry.ids[1].hi == target_id.hi) {\n"
        << "            entry.apply(source, target);\n"
        << "            return true;\n"
        << "        }\n"
        << "    return false;\n"
        << "}\n\n"
        << "}  // namespace abix_adapter\n";

    if (options.typed) {
        out
            << "\n"
            << "// Typed specializations over the generated C++ projection\n"
            << "// (namespace "
            << options.typed_namespace
            << "). Include the projection\n"
            << "// header first, then define ABIX_ADAPTER_TYPED before this header.\n"
            << "#include <abix/adapter.h>\n"
            << "#ifdef ABIX_ADAPTER_TYPED\n";
        for (size_t i = 0; i < report.maps.size(); ++i) {
            const MapRecord &map = report.maps[i];
            const std::string fn =
                adapter_symbol(map.source_name) + "_to_" + adapter_symbol(map.target_name) + "_" + std::to_string(i);
            out
                << "template <> struct ::abix::adapter<::"
                << options.typed_namespace
                << "::"
                << adapter_symbol(map.source_name)
                << "_ABIX, ::"
                << options.typed_namespace
                << "::"
                << adapter_symbol(map.target_name)
                << "_ABIX> {\n"
                << "    static bool apply(void *target, const void *source) noexcept {\n"
                << "        abix_adapter::"
                << fn
                << "(source, target);\n"
                << "        return true;\n"
                << "    }\n"
                << "};\n";
        }
        out << "#endif  // ABIX_ADAPTER_TYPED\n";
    }

    if (options.shim) {
        out
            << "\n"
            << "// C ABI shim: compile this file into a shared library and load it\n"
            << "// from a host that has no access to the C++ projection.\n"
            << "extern \"C\" {\n"
            << "std::size_t abix_adapter_count() noexcept { return abix_adapter::entry_count; }\n"
            << "bool abix_adapter_apply(const char *source_name, const char *target_name,\n"
            << "                        const void *source, void *target) noexcept {\n"
            << "    const abix_adapter::Entry *entry = abix_adapter::find(source_name, target_name);\n"
            << "    if (entry == nullptr) return false;\n"
            << "    entry->apply(source, target);\n"
            << "    return true;\n"
            << "}\n"
            << "}  // extern \"C\"\n";
    }
    return out.str();
}

}   // namespace amc
