#include "amc_lua.h"

#include <cctype>
#include <iomanip>
#include <sstream>

namespace amc {
namespace {

std::string hash_literal(Hash128 value) {
    std::ostringstream out;
    out << "0x" << std::hex << std::setfill('0') << std::setw(16) << value.hi << std::setw(16) << value.lo;
    return out.str();
}

std::string cpp_string(const std::string &value) {
    std::string result = "\"";
    for (const char c : value) {
        if (c == '\\' || c == '"') result += '\\';
        if (c == '\n')
            result += "\\n";
        else if (c == '\r')
            result += "\\r";
        else if (c == '\t')
            result += "\\t";
        else
            result += c;
    }
    return result + '"';
}

}   // namespace

std::string lua_function_symbol(std::string_view name) {
    std::string symbol;
    symbol.reserve(name.size());
    for (size_t i = 0; i < name.size(); ++i) {
        const char c = name[i];
        if (c == ':' && i + 1 < name.size() && name[i + 1] == ':') {
            symbol += '_';
            ++i;
        } else if (std::isalnum(static_cast<unsigned char>(c)) || c == '_') {
            symbol += c;
        } else {
            symbol += '_';
        }
    }
    if (symbol.empty() || std::isdigit(static_cast<unsigned char>(symbol[0]))) symbol = "_" + symbol;
    return symbol;
}

std::string lua_entry_name(std::string_view package, std::string_view name) {
    if (!package.empty()) {
        const std::string prefix = std::string(package) + "_";
        if (name.size() > prefix.size() && name.compare(0, prefix.size(), prefix) == 0)
            return std::string(name.substr(prefix.size()));
    }
    return std::string(name);
}

std::string generate_lua_contract(const AbiModule &module, std::string &error) {
    error.clear();
    const std::string package = module.package_name.empty() ? "abix_module" : module.package_name;

    std::ostringstream out;
    out
        << "// Generated by AMC from "
        << package
        << " — Aue (Lua) boundary contract.\n"
        << "// abi_hash = "
        << hash_literal(abi_hash(module))
        << "\n"
        << "// Do not edit; regenerate with `amc generate <file.abix> -l lua -o <file.hpp>`.\n"
        << "#pragma once\n"
        << "#include \"aue/aue.h\"\n"
        << "\n"
        << "namespace amc_generated {\n"
        << "\n";

    for (const auto &function : module.functions) {
        out
            << "extern \"C\" int "
            << lua_function_symbol(function.name)
            << "(lua_State *);  // "
            << function.name
            << " signature="
            << hash_literal(function.signature)
            << "\n";
    }
    out << "\n";

    const size_t count = module.functions.empty() ? 1 : module.functions.size();
    out << "inline const aue::Entry lua_entries[" << count << "] = {\n";
    for (const auto &function : module.functions) {
        out
            << "    {"
            << cpp_string(lua_entry_name(package, function.name))
            << ", "
            << static_cast<uint32_t>(function.parameters.size())
            << ", "
            << lua_function_symbol(function.name)
            << "},\n";
    }
    if (module.functions.empty()) out << "    {nullptr, 0, nullptr},\n";
    out << "};\n\n";

    out
        << "inline const aue::Contract lua_contract = {\n"
        << "    "
        << cpp_string(package)
        << ",\n"
        << "    "
        << cpp_string(hash_literal(abi_hash(module)))
        << ",\n"
        << "    lua_entries,\n"
        << "    "
        << module.functions.size()
        << ",\n"
        << "};\n"
        << "\n"
        << "}  // namespace amc_generated\n";
    return out.str();
}

std::string generate_lua_conformance(const AbiModule &module, std::string &error) {
    error.clear();
    const std::string package = module.package_name.empty() ? "abix_module" : module.package_name;
    const std::string hash = hash_literal(abi_hash(module));

    std::ostringstream out;
    out
        << "-- Generated by AMC from "
        << package
        << " — Aue conformance script.\n"
        << "-- Compiled-time metadata drives this test; run it under L0 and L1 and\n"
        << "-- the observable output must be identical.\n"
        << "-- abi_hash = "
        << hash
        << "\n"
        << "local expected = {\n";
    for (const auto &function : module.functions)
        out << "    " << cpp_string(lua_entry_name(package, function.name)) << ",\n";
    out
        << "}\n"
        << "local seen = 0\n"
        << "for _, name in ipairs(expected) do\n"
        << "    assert(type(counter[name]) == \"function\", \"missing binding: \" .. name)\n"
        << "    seen = seen + 1\n"
        << "end\n"
        << "assert(counter._module == "
        << cpp_string(package)
        << ", \"module mismatch\")\n"
        << "assert(counter._abi_hash == "
        << cpp_string(hash)
        << ", \"abi hash mismatch\")\n"
        << "print(\"aue-conformance\", seen, counter._module)\n";
    return out.str();
}

}   // namespace amc
