[package]
name = "counter"
version = "1.0"

[[import]]
language = "cpp"
flags = ["-std=c++17"]
files = ["counter_api.hpp"]
symbols = ["counter_new", "counter_add", "counter_get"]

[[export]]
output = "build/counter.abix"
