#!/usr/bin/env python3

import os

OUT = os.path.join(os.path.dirname(__file__), "..", "dlls", "hotcache_dll.cpp")
N = 1000
H = 20


def main() -> None:
    lines = []
    lines.append("// Generated by tools/gen_hotcache_dll.py, do not edit manually.")
    lines.append('#include "abix/abix.hpp"')
    lines.append("")
    lines.append("namespace {")
    for i in range(N):
        lines.append(f"int e_{i:04d}(int v) {{ return v + {i}; }}")
    lines.append("")
    for k in range(H):
        lines.append(f"int h_{k:02d}(int v) {{ return v + {k}; }}")
    lines.append("} // namespace")
    lines.append("")
    lines.append("SKL_ABIX_DEFINE_TABLE(")
    for i in range(N):
        comma = "," if (i < N - 1 or H > 0) else ""
        lines.append(f'    SKL_ABIX_ENTRY("e_{i:04d}", e_{i:04d}){comma}')
    for k in range(H):
        comma = "," if k < H - 1 else ""
        lines.append(f'    SKL_ABIX_ENTRY("h_{k:02d}", h_{k:02d}){comma}')
    lines.append(")")
    lines.append("")
    body = "\n".join(lines)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(body)
    print(f"generated {OUT}: {N} regular + {H} hot functions")


if __name__ == "__main__":
    main()